name: Release zip

on:
  push:
    branches: [master, feature/ci]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: build with pyinstaller
      run: |
        pyinstaller --noconfirm main.py
        powershell Compress-Archive dist dist.zip
        dir
    - name: Create release
      id: create_release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist.zip
        asset_name: dist.zip
        tag: ${{ github.ref }}
        overwrite: true
